#ifndef OBJECT_TYPE_H_INCLUDED
#define OBJECT_TYPE_H_INCLUDED

enum ObjectType {
    AG_TYPE_BASE_MODEL = 0,
    AG_TYPE_BASE_CAMERA,
    AG_TYPE_ASSIMP_MODEL,
    AG_TYPE_SIMPLE_MODEL,
    AG_TYPE_ORB_CAMERA,
    AG_TYPE_CAMERA,
    AG_TYPE_DIRECT_LIGHT,
    AG_TYPE_GROUP_MODEL
};

extern const char* AG_OBJECT_TYPE_NAME[];

#endif // OBJECT_TYPE_H_INCLUDED
